INSERT INTO planet (id, planet_node, planet_name) VALUES(1, 'A',	'Earth');
INSERT INTO planet (id, planet_node, planet_name) VALUES(2, 'B',	'Moon');
INSERT INTO planet (id, planet_node, planet_name) VALUES(3, 'C',	'Jupiter');
INSERT INTO planet (id, planet_node, planet_name) VALUES(4, 'D',	'Venus');
INSERT INTO planet (id, planet_node, planet_name) VALUES(5, 'E',	'Mars');
INSERT INTO planet (id, planet_node, planet_name) VALUES(6, 'F',	'Saturn');
INSERT INTO planet (id, planet_node, planet_name) VALUES(7, 'G',	'Uranus');
INSERT INTO planet (id, planet_node, planet_name) VALUES(8, 'H',	'Pluto');
INSERT INTO planet (id, planet_node, planet_name) VALUES(9, 'I',	'Neptune');
INSERT INTO planet (id, planet_node, planet_name) VALUES(10, 'J',	'Mercury');
INSERT INTO planet (id, planet_node, planet_name) VALUES(11, 'K',	'Alpha Centauri');
INSERT INTO planet (id, planet_node, planet_name) VALUES(12, 'L',	'Luhman 16');
INSERT INTO planet (id, planet_node, planet_name) VALUES(13, 'M',	'Epsilon Eridani');
INSERT INTO planet (id, planet_node, planet_name) VALUES(14, 'N',	'Groombridge 34');
INSERT INTO planet (id, planet_node, planet_name) VALUES(15, 'O',	'Epsilon Indi');
INSERT INTO planet (id, planet_node, planet_name) VALUES(16, 'P',	'Tau Ceti');
INSERT INTO planet (id, planet_node, planet_name) VALUES(17, 'Q',	'Kapteyn''s star');
INSERT INTO planet (id, planet_node, planet_name) VALUES(18, 'R',	'Gliese 687');
INSERT INTO planet (id, planet_node, planet_name) VALUES(19, 'S',	'Gliese 674');
INSERT INTO planet (id, planet_node, planet_name) VALUES(20, 'T',	'Gliese 876#');
INSERT INTO planet (id, planet_node, planet_name) VALUES(21, 'U',	'Gliese 832');
INSERT INTO planet (id, planet_node, planet_name) VALUES(22, 'V',	'Fomalhaut');
INSERT INTO planet (id, planet_node, planet_name) VALUES(23, 'W',	'Virginis');
INSERT INTO planet (id, planet_node, planet_name) VALUES(24, 'X',	'HD 102365');
INSERT INTO planet (id, planet_node, planet_name) VALUES(25, 'Y',	'Gliese 176');
INSERT INTO planet (id, planet_node, planet_name) VALUES(26, 'Z',	'Gliese 436');
INSERT INTO planet (id, planet_node, planet_name) VALUES(27, 'A''',	'Pollux');
INSERT INTO planet (id, planet_node, planet_name) VALUES(28, 'B''',	'Gliese 86');
INSERT INTO planet (id, planet_node, planet_name) VALUES(29, 'C''',	'HIP 57050');
INSERT INTO planet (id, planet_node, planet_name) VALUES(30, 'D''',	'Piscium');
INSERT INTO planet (id, planet_node, planet_name) VALUES(31, 'E''',	'GJ 1214');
INSERT INTO planet (id, planet_node, planet_name) VALUES(32, 'F''',	'Upsilon Andromedae');
INSERT INTO planet (id, planet_node, planet_name) VALUES(33, 'G''',	'Gamma Cephei');
INSERT INTO planet (id, planet_node, planet_name) VALUES(34, 'H''',	'HD 176051');
INSERT INTO planet (id, planet_node, planet_name) VALUES(35, 'I''',	'Gliese 317');
INSERT INTO planet (id, planet_node, planet_name) VALUES(36, 'J''',	'HD 38858');
INSERT INTO planet (id, planet_node, planet_name) VALUES(37, 'K''',	'Ursae Majoris');

INSERT INTO routes (id, planet_origin, planet_dest, distance) VALUES(1, 'A', 'B', 0.44);
INSERT INTO routes (id, planet_origin, planet_dest, distance) VALUES(2, 'A', 'C', 1.89);
INSERT INTO routes (id, planet_origin, planet_dest, distance) VALUES(3, 'A', 'D', 0.10);
INSERT INTO routes (id, planet_origin, planet_dest, distance) VALUES(4, 'B', 'H', 2.44);
INSERT INTO routes (id, planet_origin, planet_dest, distance) VALUES(5, 'B', 'E', 3.45);
INSERT INTO routes (id, planet_origin, planet_dest, distance) VALUES(6, 'C', 'F', 0.49);
INSERT INTO routes (id, planet_origin, planet_dest, distance) VALUES(7, 'D', 'L', 2.34);
INSERT INTO routes (id, planet_origin, planet_dest, distance) VALUES(8, 'D', 'M', 2.61);
INSERT INTO routes (id, planet_origin, planet_dest, distance) VALUES(9, 'H', 'G', 3.71);
INSERT INTO routes (id, planet_origin, planet_dest, distance) VALUES(10, 'E', 'I', 8.09);
INSERT INTO routes (id, planet_origin, planet_dest, distance) VALUES(11, 'F', 'J', 5.46);
INSERT INTO routes (id, planet_origin, planet_dest, distance) VALUES(12, 'F', 'K', 3.67);
INSERT INTO routes (id, planet_origin, planet_dest, distance) VALUES(13, 'G', 'Z', 5.25);
INSERT INTO routes (id, planet_origin, planet_dest, distance) VALUES(14, 'I', 'Z', 13.97);
INSERT INTO routes (id, planet_origin, planet_dest, distance) VALUES(15, 'I', 'J', 14.78);
INSERT INTO routes (id, planet_origin, planet_dest, distance) VALUES(16, 'L', 'T', 15.23);
INSERT INTO routes (id, planet_origin, planet_dest, distance) VALUES(17, 'T', 'N', 10.43);
INSERT INTO routes (id, planet_origin, planet_dest, distance) VALUES(18, 'T', 'S', 14.22);
INSERT INTO routes (id, planet_origin, planet_dest, distance) VALUES(19, 'S', 'O', 6.02);
INSERT INTO routes (id, planet_origin, planet_dest, distance) VALUES(20, 'O', 'U', 5.26);
INSERT INTO routes (id, planet_origin, planet_dest, distance) VALUES(21, 'J', 'R', 12.34);
INSERT INTO routes (id, planet_origin, planet_dest, distance) VALUES(22, 'R', 'P', 10.10);
INSERT INTO routes (id, planet_origin, planet_dest, distance) VALUES(23, 'R', 'L', 9.95);
INSERT INTO routes (id, planet_origin, planet_dest, distance) VALUES(24, 'Z', 'Y', 18.91);
INSERT INTO routes (id, planet_origin, planet_dest, distance) VALUES(25, 'Y', 'Q', 22.04);
INSERT INTO routes (id, planet_origin, planet_dest, distance) VALUES(26, 'Q', 'X', 10.51);
INSERT INTO routes (id, planet_origin, planet_dest, distance) VALUES(27, 'L''', 'X', 23.61);
INSERT INTO routes (id, planet_origin, planet_dest, distance) VALUES(28, 'X', 'K''', 19.94);
INSERT INTO routes (id, planet_origin, planet_dest, distance) VALUES(29, 'P', 'U', 9.31);
INSERT INTO routes (id, planet_origin, planet_dest, distance) VALUES(30, 'U', 'K''', 21.23);
INSERT INTO routes (id, planet_origin, planet_dest, distance) VALUES(31, 'U', 'J''', 25.96);
INSERT INTO routes (id, planet_origin, planet_dest, distance) VALUES(32, 'J''', 'V', 3.16);
INSERT INTO routes (id, planet_origin, planet_dest, distance) VALUES(33, 'K''', 'V', 20.42);
INSERT INTO routes (id, planet_origin, planet_dest, distance) VALUES(34, 'J''', 'I''', 17.10);
INSERT INTO routes (id, planet_origin, planet_dest, distance) VALUES(35, 'Y', 'A''', 19.52);
INSERT INTO routes (id, planet_origin, planet_dest, distance) VALUES(36, 'A''', 'B''', 31.56);
INSERT INTO routes (id, planet_origin, planet_dest, distance) VALUES(37, 'B''', 'C''', 23.13);
INSERT INTO routes (id, planet_origin, planet_dest, distance) VALUES(38, 'K''', 'W', 28.89);
INSERT INTO routes (id, planet_origin, planet_dest, distance) VALUES(39, 'W', 'C''', 10.64);
INSERT INTO routes (id, planet_origin, planet_dest, distance) VALUES(40, 'W', 'E''', 36.19);
INSERT INTO routes (id, planet_origin, planet_dest, distance) VALUES(41, 'C''', 'D''', 36.48);
INSERT INTO routes (id, planet_origin, planet_dest, distance) VALUES(42, 'E''', 'E''', 41.26);
INSERT INTO routes (id, planet_origin, planet_dest, distance) VALUES(43, 'E''', 'F''', 42.07);
INSERT INTO routes (id, planet_origin, planet_dest, distance) VALUES(44, 'F''', 'G''', 17.63);
INSERT INTO routes (id, planet_origin, planet_dest, distance) VALUES(45, 'G''', 'H''', 40.48);