//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.21 at 12:28:26 AM CAT 
//


package com.shortestpath.routes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="planetNode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="planetName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="distance" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "planetNode",
    "planetName",
    "distance"
})
@XmlRootElement(name = "RouteResponse")
public class RouteResponse {

    @XmlElement(required = true)
    protected String planetNode;
    @XmlElement(required = true)
    protected String planetName;
    protected float distance;

    /**
     * Gets the value of the planetNode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanetNode() {
        return planetNode;
    }

    /**
     * Sets the value of the planetNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanetNode(String value) {
        this.planetNode = value;
    }

    /**
     * Gets the value of the planetName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanetName() {
        return planetName;
    }

    /**
     * Sets the value of the planetName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanetName(String value) {
        this.planetName = value;
    }

    /**
     * Gets the value of the distance property.
     * 
     */
    public float getDistance() {
        return distance;
    }

    /**
     * Sets the value of the distance property.
     * 
     */
    public void setDistance(float value) {
        this.distance = value;
    }

}
